### ISSUE TITLE
[Question] about Link prediction

### ISSUE THREAD

**Issue by hirune924** [ku21fan/COO-Comic-Onomatopoeia#2]
I tried Text detection and Text recognition for my own manga comics. They worked great! Thank you!
However, I have a question about Link prediction. According to the paper, the detected texts have to be correctly ordered.
> For the link annotation, we take into account the order of reading truncated texts. For example, if the word “ばさ” is separated into “ば” and “さ”, we annotate “ば” then “さ” rather than “さ” then “ば”.

How can I get this order?

**Comment by ku21fan** [comment]
Hello, 

We are glad to hear that they worked great :)

> the detected texts have to be correctly ordered.

Actually, it is not. You don't need to order the detected texts.

Specifically, we use the following sequences as an example in section 3.3.

```
Input sequence: [ド, ッ, バン, ボッ, ボ, ン]
Output sequence: [ド, ッ, <d>, ボ, ン]
```

We consider the order of reading truncated texts for the link "annotation," not link "prediction."
It means the "output" sequence of link prediction considers the order of reading truncated texts.
The "detected texts" is used as an "input" sequence of link prediction.

In our experiments (not listed in the paper), the order of detected texts does not much matter. 
When we shuffled the order of the input sequence of M4C-COO, it still worked. (e.g., the following example)
```
Input sequence: [ド, バン, ッ, ボッ, ン, ボ]
Output sequence: [ド, ッ, <d>, ボ, ン]
```

The performance gap between the shuffled input sequence and not shuffled was small.

Hope it helps,
Best.

**Comment by hirune924** [comment]
Thanks for the answer! I got it, and it was clear!
